# Generated by Django 6.1.1 on 2026-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertbl',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registertbl',
            name='name',
        ),
        migrations.AddField(
            model_name='registertbl',
            name='username',
            field=models.CharField(default='admin', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registertbl',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterModelTable(
            name='registertbl',
            table=None,
        ),
    ]
